"""add evm key associations

Revision ID: 5574ffb12a2b
Revises: daab35a40458
Create Date: 2026-06-04 07:42:58.947326

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5574ffb12a2b"
down_revision: str | Sequence[str] | None = "daab35a40458"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evm_key_associations",
        sa.Column("netuid", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False),
        sa.Column("block_from", sa.Integer(), nullable=False),
        sa.Column("block_to", sa.Integer(), nullable=False),
        sa.Column("hotkey", sa.String(), nullable=False),
        sa.Column("evm_address", sa.String(), nullable=False),
        sa.Column("block_at_ownership_proof", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("netuid", "uid", "block_from"),
    )
    op.create_table(
        "persisted_evm_key_association_periods",
        sa.Column("netuid", sa.Integer(), nullable=False),
        sa.Column("block_from", sa.Integer(), nullable=False),
        sa.Column("block_to", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("netuid", "block_from"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("persisted_evm_key_association_periods")
    op.drop_table("evm_key_associations")
    # ### end Alembic commands ###
