"""add hotkey evm associations

Revision ID: a115fc6d4687
Revises: daab35a40458
Create Date: 2026-06-02 11:01:59.494559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a115fc6d4687'
down_revision: Union[str, Sequence[str], None] = 'daab35a40458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evm_key_associations',
    sa.Column('netuid', sa.Integer(), nullable=False),
    sa.Column('hotkey', sa.String(), nullable=False),
    sa.Column('evm_address', sa.String(), nullable=False),
    sa.Column('block_at_ownership_proof', sa.Integer(), nullable=False),
    sa.Column('valid_to_block', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('netuid', 'hotkey', 'block_at_ownership_proof')
    )
    op.create_index('ix_evm_key_associations_lookup', 'evm_key_associations', ['netuid', 'block_at_ownership_proof'], unique=False)
    op.create_table('persisted_evm_key_association_periods',
    sa.Column('netuid', sa.Integer(), nullable=False),
    sa.Column('block_from', sa.Integer(), nullable=False),
    sa.Column('block_to', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('netuid', 'block_from')
    )
    op.create_index('ix_persisted_evm_key_association_periods_lookup', 'persisted_evm_key_association_periods', ['netuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_persisted_evm_key_association_periods_lookup', table_name='persisted_evm_key_association_periods')
    op.drop_table('persisted_evm_key_association_periods')
    op.drop_index('ix_evm_key_associations_lookup', table_name='evm_key_associations')
    op.drop_table('evm_key_associations')
    # ### end Alembic commands ###
