"""add weight_tasks

Revision ID: daab35a40458
Revises:
Create Date: 2026-05-25 10:59:57.701549

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "daab35a40458"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weight_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "SUCCEEDED", "FAILED", "EXPIRED", "CANCELLED", name="taskstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("identity_name", sa.String(), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=False),
        sa.Column("netuid", sa.Integer(), nullable=False),
        sa.Column("mechanism_id", sa.Integer(), nullable=False),
        sa.Column("hotkey", sa.String(), nullable=False),
        sa.Column("start_block_number", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_weight_tasks_epoch_lookup",
        "weight_tasks",
        ["identity_name", "mechanism_id", "status", "start_block_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_weight_tasks_epoch_lookup", table_name="weight_tasks")
    op.drop_table("weight_tasks")
    # ### end Alembic commands ###
